version: "3.9"

services:
  db:
    platform: linux/x86_64
    image: mysql:8
    container_name: jaego-db
    environment:
      - "MYSQL_RANDOM_ROOT_PASSWORD=true"
      - "MYSQL_DATABASE=test"
      - "MYSQL_USER=test"
      - "MYSQL_PASSWORD=test"
    ports:
      - "3310:3306"
#services:
#  db:
#    platform: linux/x86_64
#    image: mysql:8
#    container_name: jaego-db
#    environment:
#      - "MYSQL_RANDOM_ROOT_PASSWORD=true"
#      - "MYSQL_DATABASE=${MYSQL_DATABASE}"
#      - "MYSQL_USER=${MYSQL_USERNAME}"
#      - "MYSQL_PASSWORD=${MYSQL_PASSWORD}"
#    ports:
#      - "3310:3306"
